# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d827c0ee21467cadfc7db4ed0bd3e930ab1b3c45c1e00425ec17fe3ce2c6353cb93c9557f0d8ba8d44b5c03a31891d37e49dc3f985c00b128a3f1924ae0f155c

test:
  secret_key_base: 643ecb8955049fc7be35e6e316f2de0689e57ab7eb4fd69384e0d9a76668259fcc55bfa5b3df1c26ac4aa6ae9e876450e0788b1f41b449e51f14c43b02674bee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
